config/routes.rb
db/schema.rb

Dev create routes

---

app/controllers/trips_controller.rb
app/controllers/users_controller.rb
app/policies/trip_policy.rb
app/policies/user_policy.rb
app/views/trips/edit.html.erb
app/views/trips/export.html.erb
app/views/trips/new.html.erb
app/views/trips/show.html.erb
app/views/users/dashboard.html.erb
config/routes.rb
test/controllers/trips_controller_test.rb
test/policies/trip_policy_test.rb

basic routes for trips all complete

Dev create trips controller

---

app/policies/trip_policy.rb

only manager can create trip now

---

config/puma.rb

Heroku (3/4)

---

Gemfile
Gemfile.lock
app/controllers/receipts_controller.rb
app/models/receipt.rb
app/views/receipts/new.html.erb
app/views/receipts/show.html.erb
config/environments/development.rb
config/environments/production.rb
config/storage.yml
db/migrate/20200304054256_create_active_storage_tables.active_storage.rb
db/schema.rb

Adding a recipt photo now workds

Dev add cloudinary

---

app/controllers/receipts_controller.rb
app/models/receipt.rb

fixed problems with policy to delete

---

db/seeds.rb

safetynet for yamada where there has to be one trip associated with him

safety net for receipt / receipt items

---

app/views/receipts/_employer_receipt_show.html.erb

add items on receipt

---

app/views/receipt_items/new.html.erb
app/views/receipts/_employer_receipt_show.html.erb
config/routes.rb

fix routes and add view edit destroy  receipt item

---

app/controllers/trips_controller.rb
app/views/shared/_side-bar.html.erb

weird fix. will come back to it later

---

app/assets/stylesheets/components/_body.scss

added margin so content isnt covered by sidebar

---

app/views/trips/_employer_trip_show.html.erb
app/views/trips/_form.html.erb
app/views/trips/new.html.erb

Made changes from yans feedback :goat:

Dev fix css trip form show

---

app/assets/stylesheets/components/_body.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_side-bar.scss
app/views/employer/users/dashboard.html.erb
app/views/shared/_side-bar.html.erb

Css after yann advices

---

app/views/receipt_items/_form.html.erb
app/views/receipts/_form-edit.html.erb
app/views/receipts/_form.html.erb
app/views/receipts/create.html.erb
app/views/receipts/new.html.erb
app/views/trips/_form.html.erb
app/views/trips/export.html.erb

fixed forms so they work with new styling, removed redundant pages

---

app/assets/stylesheets/components/_side-bar.scss

Comment out the hover on sidebar

comment out the hover on sidebar

---

app/views/trips/_employer_trip_show.html.erb

receipts now displaying correctly

small change to display receipts correctly

---

app/assets/stylesheets/components/_body.scss
app/assets/stylesheets/components/_footer.scss
app/views/employer/users/dashboard.html.erb
app/views/employer/users/index.html.erb
app/views/trips/_employer_trip_show.html.erb
app/views/trips/index.html.erb
app/views/users/show.html.erb

fixes the pages with new sidebar

Dev fix spacing on dash

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_trip-card.scss
app/views/trips/_employer_trip_show.html.erb

Dev employer trip show styling

---

app/assets/stylesheets/components/_body.scss
app/assets/stylesheets/components/_trip-card.scss
app/views/trips/index.html.erb
yarn.lock

complete redo of the trips display page it now looks byooodiful

---

app/controllers/receipts_controller.rb

if OCR fails will assign 0

---

app/views/shared/_navbar.html.erb

Fix landing page on employee side

Fix landingpage employee

---

app/assets/stylesheets/components/_body.scss
app/assets/stylesheets/components/_trip-card.scss
app/views/trips/_collapse.html.erb
app/views/trips/_employer_trip_show.html.erb

Dev style trip show

---

app/services/ocr.rb

Dev fix ocr

---

app/javascript/packs/application.js
app/javascript/plugins/flatpickr.js
app/views/receipts/_form-edit.html.erb
app/views/receipts/_form.html.erb
app/views/trips/_form.html.erb
package.json
yarn.lock

Dev add flatpickr

---

app/javascript/packs/application.js
app/javascript/plugins/init_select2.js
app/views/trips/_form.html.erb
package.json
yarn.lock

Dev add select2

---

app/views/receipts/_form.html.erb

default to todays date for the date

---

app/javascript/employeeNavbar/toggle.js
app/javascript/packs/application.js
app/javascript/plugins/collapse_toggle.js
app/javascript/receiptEmployer/receipt-ticket.js
app/views/trips/_employer_trip_show.html.erb
app/views/trips/index.html.erb

added drop down marker js to the style trip card and fixed other js

---

app/controllers/receipts_controller.rb
app/models/trip.rb
app/views/employer/users/dashboard.html.erb

cut the time on loading dashboard

fix queries for graph

---

app/views/trips/_collapse.html.erb
app/views/trips/_employer_trip_show.html.erb

got rid of the links to receipt items and adding recipt by an employer

fixed the styling

---

app/services/ocr.rb

change to make it work with receipt for presentation

small fix to ocr to make it work with receipt

---

app/controllers/receipts_controller.rb
app/services/ocr.rb

Fix on OCR

---

app/assets/stylesheets/components/_receipt-employer-side.scss
app/views/trips/_employer_trip_show.html.erb
db/seeds.rb

Changes a line in the seeds (rand 1..10 to rand 1..3)
and uemura to mike
and yamada to adil

change seed to have max 3 items on a receipt and not breaking the style

---

app/assets/stylesheets/components/_mobile-heading.scss
app/views/receipts/_employee_receipt_heading.html.erb

final hotfix (hopefully)

---

app/controllers/receipts_controller.rb

removed the demo day demo features
